#!/bin/bash
Kokku='date';
Kuu=`date | awk -F" " '{ print $2 }'`;
Kuupaev=`date | awk -F" " '{ print $3 }'`;
Paev=`date | awk -F" " '{ print $1 }'`;
Kellaaeg=`date | awk -F" " '{ print $4 }'`;
Riik=`date | awk -F" " '{ print $5 }'`;
Aasta=`date | awk -F" " '{ print $6 }'`;
Number=`date | awk -F" " '{ print $4 }' | awk -F: '{ print $2 }'`;
echo "Tanane kuupaev on ${Kuu} ${Kuup2ev} ${Aasta}. Kell on ${Kellaaeg}. See on ${Riik} aeg." > /home/alex/temp/proov_cron${Number}.txt
